### PR TITLE
Merge discvr-21.7 to develop

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Comment by bbimber** [comment]
@labkey-jeckels @labkey-tchad: these PRs are scripted. if you would like anyone else used as the default reviewers I'm happy to make that change

**Comment by labkey-jeckels** [comment]
@bbimber since you're primarily relying on us to approve the PR due to our repo's PR merge rules (and not for a thorough code review), could we add someone else from your side to handle the routine review duty? We can approve if others are unavailable, but this might get you faster approvals on average.

**Review by labkey-jeckels — APPROVED** [review]

**Comment by bbimber** [comment]
@labkey-jeckels What do you mean by "my side"? My lab? ONPRC?

I thought this needed to be a LK employee? If it doesnt need to be a LK employee, can I get approval power?

**Comment by labkey-jeckels** [comment]
It needs to be another person with write access to the repo, and can't be the person who opened the PR. You're the only non-LK person with write access to our fork at the moment, but we can add others if you'd let us know who should be on the list.

**Comment by bbimber** [comment]
got it. can you please add the github users jctrotter and hextraza? I'll use them going forward so we dont need to bother you

**Comment by labkey-jeckels** [comment]
Invites sent for LabDevKitModules, DiscvrLabKeyModules, and BimberLabKeyModules

**Comment by bbimber** [comment]
thanks

**Pull request merged**
