### PR TITLE
Merge discvr 20.11 to develop

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]
There's a build failure on a CSV reader dependency:

/mnt/teamcity/work/5d8c476e6f48e7d1/server/modules/DiscvrLabKeyModules/singlecell/api-src/org/labkey/api/singlecell/CellHashingService.java:3: error: package au.com.bytecode.opencsv does not exist
import au.com.bytecode.opencsv.CSVReader;

**Comment by bbimber** [comment]
@labkey-jeckels got it, thanks. trunk is more strict than 20.11 i suppose. that package is used in singlecell-api and singlecell module. do I need to add apiImplementation and implementation to uild.gradle?

implementation "net.sf.opencsv:opencsv:${opencsvVersion}"

**Comment by bbimber** [comment]
@labkey-jeckels I checked in the change to add opencsv. i dont see the TeamCity build, but hopefully this works.

**Comment by labkey-jeckels** [comment]
Build looks happy now. Tests are running. https://teamcity.labkey.org/buildConfiguration/bt312/1239189

**Comment by bbimber** [comment]
@labkey-jeckels yeah, i figured teamcity out. only issue it that we're hitting errors b/c MCC module now depends on EHR and that's not part of the TC build. 

@labkey-tchad you fixed this on 20.11. is this something we need in distributitons, or on the TeamCity contig?

**Review by labkey-jeckels — APPROVED** [review]
Please hold the merge until the TeamCity configs are happy on develop, but approving to help move things forward when it's ready.

**Pull request merged**
