### PR TITLE
Merge discvr-21.3 to develop

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Comment by bbimber** [comment]
@labkey-tchad does the team city job to rebuild the sequence tools binaries automatically run when sequence_tools_install.sh changes? This has incoming changes to remove some old software that will fix tests.

**Comment by labkey-tchad** [comment]
> @labkey-tchad does the team city job to rebuild the sequence tools binaries automatically run when sequence_tools_install.sh changes? This has incoming changes to remove some old software that will fix tests.

It does but it was configured to build them from the discvr-20.7 branch. I just updated it to look at discvr-21.3 and it is queued up to build them now: https://teamcity.labkey.org/buildConfiguration/LabkeyTrunk_Dependencies_LinuxSequenceAnalysisTools?

**Comment by bbimber** [comment]
@labkey-tchad OK. It would be fine if it always built off develop, since this file changes very rarely. this would seem better to me than a specific release or discvr-* branch, so it just automatically stays up to date.

**Review by labkey-jeckels — APPROVED** [review]
Changes look fine. I know you're waiting for the test results but I'll approve so it's ready to go.

**Pull request merged**
