### PR TITLE
Upgrade JAXB 2.3.3 -> 4.0.5

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
Move to the jakarta version of JAXB

### CODE REVIEW

**Comment by bbimber** [comment]
@labkey-adam: do you still need this?

**Comment by bbimber** [comment]
@labkey-adam: removing the old jakarta-related force seems to work fine. When I run this locally, I was getting version discrepancies on angus-activation, so i added a force for this (unsure if there is a better way). If this is reasonable, would you mind promoting angusActivationVersion into the global gradle.properties? if there is a more elegant way, go for it.

**Comment by labkey-adam** [comment]
> @labkey-adam: removing the old jakarta-related force seems to work fine. When I run this locally, I was getting version discrepancies on angus-activation, so i added a force for this (unsure if there is a better way). If this is reasonable, would you mind promoting angusActivationVersion into the global gradle.properties? if there is a more elegant way, go for it.

This is great... the other version updates bring in the jakarta-packaged jaxb. But not the latest version, so I need to reconcile. And for `activation`, I've just excluded it in other places. Anyway, I'll take it from here and eliminate the discrepancies. Thanks.

**Comment by labkey-adam** [comment]
@bbimber this should do it as far as excluding `activation` and getting the correct `jaxb` version in place

**Review by bbimber — APPROVED** [review]
As long as the existing tests pass, these changes should be fine

**Comment by labkey-adam** [comment]
> As long as the existing tests pass, these changes should be fine

PostgreSQL looks good. SQL Server test suites have been delayed, but they're flowing again. I'll wait until I see green.

**Pull request merged**
