### PR TITLE
Item 7490: upgrade log4j

### PR DESCRIPTION
**Pull request by labkey-ankurj**
#### Rationale
See in related platform PR.

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/1378

### CODE REVIEW

**Review by labkey-jeckels — APPROVED** [review]

**Review by bbimber — CHANGES_REQUESTED** [review]
@labkey-ankurj What's going on with NOPLoggerRepository?  I think commenting this out will make NPEs.

**Comment by labkey-ankurj** [comment]
> @labkey-ankurj What's going on with NOPLoggerRepository? I think commenting this out will make NPEs.

Hi Ben,
We are doing this upgrade log4j work in iterations. In this first iteration, I have just updated the straight transitions of log4j1 packages to log4j2. There are a few special cases in the whole code base like this one NOPLoggerRepository for which there is no equivalent functionality in log4j2 apis. We will not merge this branch until those special cases are covered. 
thanks,
Ankur

**Comment by bbimber** [comment]
OK. as you probably saw this code isnt doing anything particularly special with the NoOpLogger.  If there is some other pattern we're supposed to follow in log4j2 we can do this instead.

**Review by bbimber — COMMENTED** [review]
@labkey-ankurj thanks - this looks good.

**Comment by labkey-ankurj** [comment]
@bbimber thanks for reviewing. Merging the branch requires your approval.

**Review by bbimber — APPROVED** [review]

**Pull request merged**
