### PR TITLE
Fix multiple typos - variable name and make "groups" singular to correctly filter on LDAP group names

### PR DESCRIPTION
**Pull request by labkey-jeckels**

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
@bbimber FYI. ONPRC is doing testing and hit a problem where the default value of "groups" didn't match the previous behavior of the hard-code "group" for filtering the LDAP queries

**Comment by bbimber** [comment]
@labkey-jeckels thanks for the note.  a couple questions:

1) I'm reading code only, but is this right?  while GROUP_OBJECTCLASS_PROP may or may not have a more appropriate default and spelling, it's easy to override in the UI, right?  OpenLdap's management UI can already be used to set this?

2) it seems like premium module might be stomping over openldap sync's admin console management link (separate issue).  Mine was here first...

3) is there anyone at WNPRC who could be queried on this?  Given they did actual testing on this module (my servers dont use it), I'd like to ping them.  If I made this option parameterized, it seems probable it was needed.  It might be that different LDAP servers use 'group' vs. 'groups'?  

I should add, the only real change I made to the LDAP code after you all stole my code and put it behind your paywall was to incorporate some flexibility required to make this work on WNPRC's LDAP.  I dont know how many groups are actively using the pirated premium module LdapSync, but I have to believe that the more LDAP servers attempt to use Ldap sync the more quirks will be found.

**Comment by labkey-jeckels** [comment]
1. Correct, on the ONPRC test server updating the property in the UI to "group" made everything work as expected.

3. Since the original code here was using "group" and the WNPRC LDAP scenario uses "top" I figured that this was a typo in the conversion process. I don't know of any servers that have been using "groups".

2. They'll have the same link text, but show up in different columns in the Admin Console when co-installed.

My intent with this change is to make it as seamless a migration from groups that were using the LDK copy to the OpenLDAPSync module as possible, including ONPRC (they'll likely restore from a DB backup multiple times before their upgrade is complete, so this will save them from having the update the setting each time).

**Comment by bbimber** [comment]
@labkey-jeckels 

Hi Josh, 

yeah, i realized i missed the duplicate 'ldap admin' link after i posted.

I think you're answering my question, but want to check: are you saying you actually looked at the WNPRC server and you can confirm they are using neither 'groups' nor 'group' and in fact use the field 'top' instead?  If that's true, then sure, make the default 'group'.

To the general question of migration/upgrades/restores: I'm sure you already know this is possible, but since there are going to be other server-specific settings to change (basically updating prop.properies), can you write them a SQL script to run after upgrade that changes emails, turns off the notification service, maybe changes color scheme, etc?  The one I used years ago when I managed PRIMe would probably basically still be correct.

**Review by bbimber — COMMENTED** [review]
Based on discussion above this is fine.

**Review by labkey-ankurj — APPROVED** [review]

**Pull request merged**
