### PR TITLE
Hard-code jaxb-api version to fix build

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
See https://github.com/LabKey/server/pull/305 for details

### CODE REVIEW

**Review by bbimber — COMMENTED** [review]
@labkey-adam: I'm 100% fine using variable instead of hard-coding. i only hard-code in our build.gradle if I didnt see a suitable variable globally (which is not as easy for me to modify)

**Comment by labkey-adam** [comment]
> @labkey-adam: I'm 100% fine using variable instead of hard-coding. i only hard-code in our build.gradle if I didnt see a suitable variable globally (which is not as easy for me to modify)

Sounds good. I'll update `jakarta.xml.bind-api` to use `${jaxbVersion}`. I hesitated because of the "mcc" comment.

Note that I'm planning to leave `force "javax.xml.bind:jaxb-api:2.3.0"` in place. You might want to `exclude` it within whichever dependency(ies) is pulling that in. I believe it's nearly identical to the renamed `jakarta.xml.bind:jakarta.xml.bind-api`.

**Comment by bbimber** [comment]
@labkey-adam, they just needed to be the same, and I dont think I can share gradle variables across repos without editing the LK platform repo. I'm 100% for making this more automatic.

**Comment by bbimber** [comment]
do you need me to update mcc in BimberLabInternal? https://github.com/LabKey/BimberLabKeyModules/blob/develop/mcc/build.gradle

**Comment by labkey-adam** [comment]
> do you need me to update mcc in BimberLabInternal? https://github.com/LabKey/BimberLabKeyModules/blob/develop/mcc/build.gradle

You might as well use the `jaxb` constant there as well. No rush though since the result will be the same.

**Comment by labkey-adam** [comment]
> @labkey-adam, they just needed to be the same, and I dont think I can share gradle variables across repos without editing the LK platform repo. I'm 100% for making this more automatic.

They can't be on the same version since there's no 2.3.3 version of `javax.xml.bind:jaxb-api`; that's why I hard-coded the previous version. `jakarta.xml.bind-api` is the successor to `javax.xml.bind:jaxb-api`. I don't know if having both (with slightly different versions) will cause problems, but I'm guessing it'd be best to use exclude so you're not pulling in `javax.xml.bind:jaxb-api` at all.

**Review by labkey-susanh — APPROVED** [review]

**Pull request merged**
