### PR TITLE
Merge discvr-20.11 to develop

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Review by labkey-jeckels — COMMENTED** [review]
Did you see what looks like a new failure in LabModulesTest?

**Review by labkey-jeckels — APPROVED** [review]
The failure could be related to the LabModules PR too, so approving this and assuming you'll investigate.

**Comment by bbimber** [comment]
@labkey-jeckels Thanks, yes, i'll look into it. Odd that I dont see this on 20.11, but perhaps there's some new kind of timing issue.

**Comment by bbimber** [comment]
@labkey-jeckels that was an odd one. I checked is JS code that called replaceAll() on a string, which isnt proper JS. i dont know why it worked on 20.11, but it was dying on the merged branch. anyway, i switched to replace() and tests are OK.

**Pull request merged**
