### PR TITLE
Merge discvr-19.3 to develop

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Review by labkey-tchad — CHANGES_REQUESTED** [review]
Getting startup errors on TeamCity:
ERROR ModuleUpgrader           2020-02-14 13:46:08,816           Module Upgrade : Failure during module upgrade
java.lang.AssertionError
	at org.labkey.api.module.DefaultModule.versionUpdate(DefaultModule.java:329)
	at org.labkey.api.module.ModuleUpgrader.upgrade(ModuleUpgrader.java:83)
	at org.labkey.api.module.ModuleUpgrader.lambda$upgrade$0(ModuleUpgrader.java:95)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by bbimber** [comment]
@labkey-adam I'll look into why this is happening and will probably update our modules to use getSchemaVersion and drop getVersion; however, i bring this error to your attention b/c from what i can tell in the code I think the intent is for "legacy" modules that havent been converted to still work?

**Comment by bbimber** [comment]
@labkey-tchad I think this was related to getVersion/getSchemaVersion.  i dont know how to kick off teamcity builds from here though.

**Comment by labkey-adam** [comment]
If it's not overridden then getSchemaVersion() defers to getVersion(). This assert is supposed to be saying if you're claiming you have scripts then you better not have a null schema version. I don't think it's a backward compatibility issue -- right now, the only way that getSchemaVersion() can be null is if you override it and set it null.

**Comment by bbimber** [comment]
@labkey-adam OK, but the point being that my Module java files were untouched, so shouldnt the build have worked?  it this expecting something to be defined in module.properties, which we do not have?  anyway, it makes sense to switch to getSchemaVersion(), which i just checked in.

**Comment by labkey-adam** [comment]
Yeah, I agree... I think I posted on the other PR that this should be a warning for now. My intent wasn't to break existing modules.

**Comment by bbimber** [comment]
@labkey-tchad I dont know for certain, but it seems like this test failure might not be related to our code?  it's failing during stopImpersonating()?  

If this is true, is it possible to approve?  Merging these will fix the problem on develop with a null getSchemaVersion().

**Review by labkey-tchad — APPROVED** [review]
That failure isn't a test bug but it doesn't appear to be a problem with this merge.

**Pull request merged**
